#!/bin/bash
# make all packages for Retrode3
#
# if we rebuild the binaries (option -b),
# this requires a Retrode3 connected and running RNDIS
# also needs to have gcc / g++ installed (apt-get install g++) there

set -e

if [ "$1" == -b ]
then
	echo build retrode tool and package
	export DEPLOY=true DEVICE=otg	# auto-install by .qcodeproj
	DEV=root@192.168.0.202	# for ssh and rsync
	CARTREADER=/Volumes/Retrode3/Retrode3-Software/Cart_Reader
	BINDIR=/usr/local/bin/
	ROOTDIR=/usr/local/games/retrode/

	cat <<END | con $DEVICE
[ "$(which g++)" || apt-get install g++
END

	echo remote build retrode-tool
	mkdir -p ./$BINDIR/ ./$ROOTDIR/
	(
		cd $CARTREADER
		make clean all remote
	)

	(
		cd retrode-tools
		echo fetch retrode binary
		cp $CARTREADER/retrode ./$BINDIR/retrode
		cp -R $CARTREADER/../sd/* ./$ROOTDIR

		echo remote build ucon64
		SRCDIR=/usr/local/src/ucon64
		rsync -rltDvzh "retrode-tools/ucon64-2.2.2-src/" "$DEV:$SRCDIR"
		cat <<END | con $DEVICE
cd
cd $SRCDIR/src
./configure --disable-parallel
make
./install.sh
END
		echo fetch ucon binary
		scp $DEV:$BINDIR/ucon64 ./$BINDIR/ucon64
	)
fi

echo "Check retrode-web-control"
for i in retrode-web-control/var/www/html/*.php;
do
	php -l $i || exit 1
done

echo "Build retrode3.deb (and subpackages)"
RECURSIVE=true ./retrode3.qcodeproj	# could make others recursively but then we have no clear list

PACKAGES+=" retrode-controller-gadget"
PACKAGES+=" retrode-tools"
PACKAGES+=" retrode-udev-rules"
PACKAGES+=" retrode-web-control"
PACKAGES+=" ucon64"
PACKAGES+=" retrode3"

echo installing Debian Packages: $PACKAGES

./dl-deb -o $PACKAGES
open http://192.168.0.202