#!/bin/bash
# make all packages for Retrode3
#
# if we rebuild the binaries (option -b),
# this requires a Retrode3 connected and running RNDIS
# also needs to have gcc / g++ installed (apt-get install g++) there

[ "$DEV" ] || DEV=root@192.168.0.202	# for ssh and rsync

set -e

BUILD_PACKAGES=true
BUILD_TOOL=false
INSTALL_PACKAGES=true

# default is not to build tools from source but pack current version (incl. other files) and install

while [ "$1" ]
do
	case "$1" in
		-b ) BUILD_TOOL=true;;
		-np ) BUILD_PACKAGES=false; INSTALL_PACKAGES=false;;	# no pack
		-ni ) INSTALL_PACKAGES=false;;	# no install
		-* ) echo unknown option "$1"; exit 1;;
		* ) break;
	esac
	shift
done

if $BUILD_TOOL
then
	echo build retrode tools and packages
	export DEPLOY=false # do not auto-install by .qcodeproj	# DEPLOY will damage the permissions of / or /etc/sudoers.d
	CARTREADER=$(cd ../Retrode3-OSCR; pwd)
	BINDIR=/usr/local/bin/
	ROOTDIR=/usr/local/games/oscr/

	echo build oscr command line tool &&
	(
		cd retrode3-tools
		mkdir -p ./$BINDIR/ ./$ROOTDIR/ ./$BINDIR/../include ./$BINDIR/../lib ./$BINDIR/../man/man1 ./$BINDIR/../man/man3
		( cd $CARTREADER && make clean all && make clean all ARCH=mipsel )	# makes local version with HOSTCC to find bugs early and then remote
		echo fetch oscr binary
		cp $CARTREADER/oscr ./$BINDIR/oscr
		cp $CARTREADER/oscr.groff ./$BINDIR/../man/man1/oscr.groff	# man page
		cp $CARTREADER/retrode3-lib.h ./$BINDIR/../include/retrode3-lib.h
		cp $CARTREADER/retrode3-lib.o ./$BINDIR/../lib/retrode3-lib.o
		cp $CARTREADER/retrode3-lib.groff ./$BINDIR/../man/man3/retrode3-lib.groff	# man page
		cp -R $CARTREADER/sd/* ./$ROOTDIR
	)

	false &&	# no longer needed since we can cross-compile ucon64 now
	echo remote build ucon64 &&
	(
		cd retrode3-tools
		SRCDIR=/usr/local/src/ucon64
		rsync -rltDvzh "./ucon64-2.2.2-src/" "$DEV:$SRCDIR"
		cat <<END | ssh $DEV
cd
cd $SRCDIR/src
./configure --disable-parallel
make
./install.sh
END
		echo fetch ucon binary
		scp $DEV:$BINDIR/ucon64 ./$BINDIR/ucon64
	)
fi

echo "Check retrode3-web-control"
for i in retrode3-web-control/var/www/html/*.php;
do
	php -l $i || exit 1
done

echo "Prepare zipped groff man pages"
find . -name '*.groff' | while read MANFILE
do
	DIR=$(dirname "$MANFILE")/../
	BASE=$(basename "$MANFILE" .groff)
	SECTION=$(fgrep '.TH man ' <"$MANFILE" | cut -d ' ' -f 3)
	[ "$SECTION" ] && mkdir -p $DIR/../man/man$SECTION && gzip <$MANFILE >$DIR/../man/man$SECTION/$BASE.$SECTION.gz
done

if $BUILD_PACKAGES
then

echo "Build retrode3.deb (and subpackages)"
RECURSIVE=true ./retrode3.qcodeproj	# could make others recursively but then we have no clear list
fi

if $INSTALL_PACKAGES
then

PACKAGES+=" retrode3-hidd"
PACKAGES+=" retrode3-controller-gadget"
PACKAGES+=" retrode3-storage-gadget"
PACKAGES+=" retrode3-smb"
PACKAGES+=" retrode3-udev-rules"
PACKAGES+=" retrode3-web-control"
PACKAGES+=" oscr"
PACKAGES+=" ucon64"
PACKAGES+=" retrode3-tools"
PACKAGES+=" retrode3"

echo installing Debian Packages: $PACKAGES

dl-deb -o $PACKAGES

open http://192.168.0.202

fi
