#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          retread-controller-gadget
# Required-Start:    letux-gadget
# Required-Stop:
# Default-Start:     
# Default-Stop:      0 1 2 3 4 5 6
# Short-Description: Control hidd /dev/ttyHID0
# Description:       This script adds a controller device
#                    
### END INIT INFO

# Author: H. Nikolaus Schaller <hns@goldelico.com>

SERVICE=retread-controller-gadget
DEVICE=ttyHID0

do_status () {
	if [ -e /dev/ttyHID0 ] ; then
		echo "$SERVICE is running."
		return 0
	else
                return 4
        fi
}

case "$1" in
  start)
	log_daemon_msg "Starting $SERVICE"
	/etc/gadget/core/letux-gadget.sh add hid
	daemon -r --name=$SERVICE -- hidd $DEVICE
	exit 0
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	log_daemon_msg "Stopping $SERVICE"
	daemon --name=$SERVICE --stop 2>/dev/null
	/etc/gadget/core/letux-gadget.sh remove hid
	log_progress_msg "disabled."
	log_end_msg 0
	exit 0
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: $0 start|stop|status" >&2
	exit 3
	;;
esac

:
